plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-capybara
  - rubocop-rspec_rails

require:
  - rubocop-slim

AllCops:
  NewCops: enable

RSpec/MultipleMemoizedHelpers:
  Max: 6
