services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      ELEVATE_DATABASE_USER: postgres
      ELEVATE_DATABASE_PASSWORD: password
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data:
