default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: postgres
  password: password
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>

development:
  <<: *default
  database: elevate_development

test:
  <<: *default
  database: elevate_test<%= ENV['TEST_ENV_NUMBER'] %>
  username: <%= ENV["ELEVATE_DATABASE_USER"] || "postgres" %>
  password: <%= ENV["ELEVATE_DATABASE_PASSWORD"] || "postgres" %>
  host: <%= ENV["ELEVATE_DATABASE_HOST"] || "localhost" %>

production:
  primary: &production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  queue:
    <<: *production

  cache:
    <<: *production

  cable:
    <<: *production
