default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: elevate_development

test:
  <<: *default
  database: elevate_test

production:
  primary: &primary_production
    <<: *default
    database: elevate_production
    username: elevate
    password: <%= ENV["ELEVATE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: elevate_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: elevate_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: elevate_production_cable
    migrations_paths: db/cable_migrate
