default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV.fetch("ELEVATE_DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("ELEVATE_DATABASE_PASSWORD", "password") %>
  host: <%= ENV.fetch("ELEVATE_DATABASE_HOST", ENV.fetch("DATABASE_HOST", "localhost")) %>

development:
  <<: *default
  database: elevate_development

test:
  <<: *default
  database: elevate_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  primary: &production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  queue:
    <<: *production

  cache:
    <<: *production

  cable:
    <<: *production

