name: RSpec

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  rspec:
    name: Run RSpec
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 2s
          --health-retries 3

    env:
      RAILS_ENV: test
      ELEVATE_DATABASE_USER: postgres
      ELEVATE_DATABASE_PASSWORD: postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.2'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Prepare test databases
        run: bundle exec rails parallel:prepare

      - name: Run RSpec in parallel
        run: bundle exec parallel_rspec spec -n 4
