name: RSpec

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  rspec:
    name: Run RSpec
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 2s
          --health-retries 5

    env:
      RAILS_ENV: test
      ELEVATE_DATABASE_USER: postgres
      ELEVATE_DATABASE_PASSWORD: postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install headless browser dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 \
            libxcomposite1 libxdamage1 libxrandr2 libgbm1 \
            libasound2t64 libpangocairo-1.0-0 libgtk-3-0 libdrm2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Create test database
        run: bundle exec rails db:create

      - name: Run migrations
        run: bundle exec rails db:migrate

      - name: Prepare test databases
        run: bundle exec rails parallel:prepare

      - name: Run RSpec in parallel
        run: bundle exec parallel_rspec spec -n 4
